// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cilgwgzengkdgerdztdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbGd3Z3plbmdrZGdlcmR6dGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjI5NjgsImV4cCI6MjA3MDczODk2OH0.EA-ZvV2NLo3Whnge3dI1wDzmmB1qNVvEZOXldRChx1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});